### ISSUE TITLE
Missing flex properties

### ISSUE THREAD

**Issue by hermagrini** [addyosmani/critical#146]
I encountered an issue while implementing the critical path(with gulp) when using `flex` properties.
If I have a class like this:
```css
.example {
  padding: 12% 0 18%;
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
}
```
Then the output from `critical` is:
```css
.example {
  padding: 12% 0 18%;
}
```
I tried the same using `Penthouse` and it does correctly output the `flex` properties.

I do not know if there's an issue with my setup, or what's going on. Currently the build process goes like this:

1. Compile SASS
2. Minify and concat
3. Generate Critical

The task looks like this:

```javascript
  return gulp.src(['build/index.html'])
    .pipe(critical({
      base    : 'build/',
      height  : 1080,
      css     : ['build/assets/stylesheets/application.css', 'build/assets/stylesheets/components/landingpage.css'],
      width   : 1920,
      inline  : true,
      minify  : false
    }))
    .pipe(gulp.dest('build'));
```

It happens whether I specify the css or not, whether inline or not and regardless the dimensions used
