### ISSUE TITLE
How resolve all css url(...) ?

### ISSUE THREAD

**Issue by retyui** [addyosmani/critical#236]
## My code:
```js
critical.generate({
	src: "http://url",
	minify: false,
	timeout: 3*60000,
	dimensions: [
		{
			width: 360,
			height: 639
		}, {
			height: 270 * 4,
			width: 320 * 4
		}
	]
});
```
## Result:
```css
.product-reviews-summary{
	background-image:url(../images/rating-bar.png);
	line-height:1;
	margin:7px 0;
	background-position:50% 50%;
	background-repeat:no-repeat no-repeat;
}
```
## Expected Result:
```css
.product-reviews-summary{
	background-image:url(http://url/any/path/to/my/assets/images/rating-bar.png);
	line-height:1;
	margin:7px 0;
	background-position:50% 50%;
	background-repeat:no-repeat no-repeat;
}
```
