### ISSUE TITLE
Extract is not working

### ISSUE THREAD

**Issue by julia-dizhak** [addyosmani/critical#253]
there is  an extract from available options
```
{
 css: ['dist/styles/main.css'],
 extract: true,
}
```
which supposed to extract inlined styles from referenced stylesheets
But it's not working

**Comment by bezoerb** [comment]
@julia-dizhak: extract only works in combination with `inline: true` as this is handled by `inline-critical`.

**Comment by pocketjoso** [comment]
@bezoerb would be nice for critical to output a warning when it's run with these incompatible settings

**Comment by AlexMiroshnikov** [comment]
I suspect that `extract` now doesn't work even when `inline: true` is set. Not 100% sure yet, but I'm going to provide a minimalistic sample.

**Comment by lili21** [comment]
same issue here. extract not working.

**index.html**

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Critical</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <div id="root"></div>
</body>
</html>
```

**style.css**

```css
body,
html {
  height: 100%;
  font-family: PingFang SC, Helvetica Neue, Helvetica, STHeitiSC-Light, Arial, sans-serif;
  line-height: 1.5;
  font-size: .37333rem;
  -webkit-font-smoothing: antialiased
}

#root {
  height: 100%;
  width: 10rem;
  margin: 0 auto
}

.Home-page--home__PLzhO {
  margin-top: 1.06667rem
}

.Home-page--home__PLzhO a {
  display: block;
  padding: .26667rem 0;
  text-align: center;
  font-size: .42667rem;
  font-weight: 700;
  color: #66ab93
}
```

after execute

```bash
critical dist/index.html -iem > dist/index-critical.html
```

**index-critical.html**

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Critical</title>
  <style>
    body,html{height:100%;font-family:PingFang SC,Helvetica Neue,Helvetica,STHeitiSC-Light,Arial,sans-serif;line-height:1.5;font-size:.37333rem;-webkit-font-smoothing:antialiased}#root{height:100%;width:10rem;margin:0 auto}
  </style>
  <link rel="preload" href="style.css" as="style" onload="this.onload=null;this.rel='stylesheet'">
  <noscript><link rel="stylesheet" href="style.css"></noscript>
  <script>!function(n){"use strict";n.loadCSS||(n.loadCSS=function(){});var o=loadCSS.relpreload={};if(o.support=function(){var e;try{e=n.document.createElement("link").relList.supports("preload")}catch(t){e=!1}return function(){return e}}(),o.bindMediaToggle=function(t){var e=t.media||"all";function a(){t.media=e}t.addEventListener?t.addEventListener("load",a):t.attachEvent&&t.attachEvent("onload",a),setTimeout(function(){t.rel="stylesheet",t.media="only x"}),setTimeout(a,3e3)},o.poly=function(){if(!o.support())for(var t=n.document.getElementsByTagName("link"),e=0;e<t.length;e++){var a=t[e];"preload"!==a.rel||"style"!==a.getAttribute("as")||a.getAttribute("data-loadcss")||(a.setAttribute("data-loadcss",!0),o.bindMediaToggle(a))}},!o.support()){o.poly();var t=n.setInterval(o.poly,500);n.addEventListener?n.addEventListener("load",function(){o.poly(),n.clearInterval(t)}):n.attachEvent&&n.attachEvent("onload",function(){o.poly(),n.clearInterval(t)})}"undefined"!=typeof exports?exports.loadCSS=loadCSS:n.loadCSS=loadCSS}("undefined"!=typeof global?global:this);</script>
</head>
<body>
  <div id="root"></div>
</body>
</html>
```

and the **style.css** still contain the inlined style. I'm using `critical@1.3.3`
