### ISSUE TITLE
How to generate critical css for lots of multiples pages serially?

### ISSUE THREAD

**Issue by pratham2003** [addyosmani/critical#320]
Presently this is my gulp task.
`gulp.task('critical', function (cb) {

var promises = [];

  Object.keys(CRITICALCSS.pages).forEach(function(key){
    promises.push(critical.generate({
      base: '/',
      src: CRITICALCSS.base_url + CRITICALCSS.pages[key],
      css: [
        'dist/assets/css/app.css'
      ],
      styleTarget: 'dist/assets/css/critical/' + key + '.css',
      minify: true,
      dimensions: [
        { width: 375, height: 1200 },
        { width: 1024, height: 1400 },
        { width: 1280, height: 1500 }
      ],
      ignore: ['@font-face'],
      include: [
        '.foundation-mq',
        '.is-dropdown-submenu'
      ]
    }));
  });

  return Promise.all(promises)
    .then( cb() )
    .catch((e) => {
        console.error(e.message);
    });
});
`

CRITICALCSS is defined in my config.yml
`# Critical CSS Base URL
CRITICALCSS:
  base_url: "http://some-example.com"
  pages:
    front-page: "/"
    page-13: "/?p=13"
    page-16: "/?p=16"
    fallback: "/?p=1427"`

When I watch my access log with `tail -f log_file_name` I notice that all the 4 pages are called in parallel.
I would want them to run serially or at-least 1 at a time.

Any thoughts on what I could do to achieve this? My `CRITICALCSS.pages` will grow a lot later. Running this in parallel might not be possible due to memory constraints.

**Comment by bezoerb** [comment]
Maybe you can try something like this:
https://github.com/petkaantonov/bluebird/issues/70#issuecomment-300474409

**Comment by bezoerb** [comment]
Had some thoughts on adding this feature to critical along with an option for 'concurrency' and **maybe** an option to merge the resulting css into one which could be used for multiple pages.

**Comment by pratham2003** [comment]
I ended up using [es6-promise-pool](https://www.npmjs.com/package/es6-promise-pool)

Works nicely.
Remember to set concurrency to 1 or 2 if you are using XAMPP.
XAMPP isn't meant to handle concurrent requests very well.

config-example.yaml
# Critical CSS Base URL
CRITICALCSS:
```
  base_url: "http://example.com"
  concurrency: 2
  pages:
    front-page: "/"
    page-392: "/?p=392"
    page-382: "/?p=382"
    special-category-fallback: "/?p=1820"
    global-fallback: "/?p=1427"
```

my gulp critical task
```
gulp.task('critical', /*['build'],*/ function (cb) {

  // constructing array out of list-object returned by config.yaml so I can pop each item.
  var pages = Object.keys(CRITICALCSS.pages).map(function(val){
    return { key: val, url: CRITICALCSS.pages[val] };
  });

  // Modified example code from promiseProducer docs
  var promiseProducer = function() {
    const page = pages.pop();
    if (!page) {
      return null;
    }

    // critical.generate returns a Promise.
    return critical.generate({
      base: '/',
      src: CRITICALCSS.base_url + page.url,
      css: [
        'dist/assets/css/app.css'
      ],
      styleTarget: 'dist/assets/css/critical/' + page.key + '.css',
      minify: true,
      dimensions: [
        { width: 375, height: 1200 },
        { width: 1024, height: 1400 },
        { width: 1280, height: 1500 }
      ],
      ignore: ['@font-face'],
      include: [
        '.foundation-mq',
        '.is-dropdown-submenu',
      ]
    })
  }

  var pool = new PromisePool(promiseProducer, CRITICALCSS.concurrency)

  var poolPromise = pool.start();

  poolPromise.then(function () {
    console.log('All critical css files generated');
    cb();
  }, function (error) {
    console.log('Failed to generate all/some critical css files: ' + error.message)
  })

});
```

**Comment by jyoseph** [comment]
@pratham2003 Thanks for your code example! When I run it, I get this...

> ReferenceError: CRITICALCSS is not defined

I'm assuming this is because I need to read the yaml file. Would you be able to show your entire gulp file? It would be a huge help to me. Thank you!

**Comment by pratham2003** [comment]
@jyoseph There might have been some changes to my config.yml
I can't upload my entire gulp file.

The CRITICALCSS section at present it looks something like this.
```
CRITICALCSS:
  base_url:
    dev: "https://dev.example.com"
    production: "https://www.example.com"
  concurrency: 1
  pages:
    front-page: "/"
    blog-page: "/blog/"
    for-fallback: "/dummy-page"
    page-1: "/page/1/"
    page-2: "/page/2/"
    page-3: "/page/3/"
```
