### ISSUE TITLE
[question] Is it possible to disable evaluation and rebasing?

### ISSUE THREAD

**Issue by egorovli** [addyosmani/critical#359]
Hi. I'm trying to use `critical` with `Next.js` and `css-modules` to inline critical css on page request, but I can't seem to figure out the correct options. Currently I have a helper method injected in `req` object:

In `_document.jsx`:

```js
// ...
let html = ReactDOM.renderToStaticMarkup(<App {...props} />)
let styles = await ctx.req.gimmeStyles(html)
// ...
```

A helper method:

```js
server.use(async (ctx, next) => {
  ctx.req.gimmeStyles = async (html = '') => {
    if (!html) {
      return ''
    }

    let { css } = await critical.generate({
      base: './',
      html,
      css: cssFiles
    })

    return css
  }

  return next()
})
```

So basically I just pass a list of generated CSS files and HTML markup as a string. I tried using it without the `base` option, but it `critical` produces warnings in the console. If I use the `base` option, some assets in the inlined CSS get rebased.

Source CSS:

```css
@font-face {
  font-family: Inter;
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(/_next/static/assets/fonts/inter/inter-regular.woff2?h=bffaed79) format("woff2"),
       url(/_next/static/assets/fonts/inter/inter-regular.woff?h=aebfbb3c) format("woff")
}
```

Inlined CSS (`base: './'`):

```css
@font-face {
  font-family: Inter;
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(/.next/static/css/_next/static/assets/fonts/inter/inter-regular.woff2) format("woff2"),
       url(/.next/static/css/_next/static/assets/fonts/inter/inter-regular.woff) format("woff")
}
```

Inlined CSS (`base: nextPath)`):

```css
@font-face {
  font-family: Inter;
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(/static/css/_next/static/assets/fonts/inter/inter-regular.woff2) format("woff2"),
       url(/static/css/_next/static/assets/fonts/inter/inter-regular.woff) format("woff")
}
```

If I use `base: path.join(nextPath, 'static', 'css')` it works only if assets don't have CDN prefix:

Source CSS:

```css
@font-face {
  font-family: Inter;
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(http://127.0.0.1:8080/_next/static/assets/fonts/inter/inter-regular.woff2?h=bffaed79) format("woff2"),
       url(http://127.0.0.1:8080/_next/static/assets/fonts/inter/inter-regular.woff?h=aebfbb3c) format("woff")
}
```

Inlined CSS (`base: path.join(nextPath, 'static', 'css')`):

```css
@font-face {
  font-family: Inter;
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(/styles.c9d869dd.chunk.css) format("woff2"),
       url(/styles.c9d869dd.chunk.css) format("woff")
}
```

🤷🏼‍♂️

How can I disable processing of `url()` and such entirely?
